version: "3.8"
services:
  db:
    build: .
    container_name: filmotheque-db
    ports:
      - "27017:27017"
  opensesame-back:
    build:
      context: ./opensesame-back
      dockerfile: Dockerfile
    container_name: opensesame-back
    environment:
      NODE_ENV: production
      PORT: 8080
      DB_NAME: opensesame
      DATABASE: mongodb://admindb:admindb@db:27017/opensesame?authSource=admin
      PASSWORD_HASH_DIFFICULTY: 12
      JWT_SECRET: jc2TNsWyaM3DdKkhurJL8QGzCvX9BfUY
      JWT_EXPIRES_IN: 7d
      JWT_COOKIE_EXPIRES_IN: 7
      RATELIMIT_MAXCONNECTIONS: 100
      RATELIMIT_WINDOWMS: 3600000
      CORS_WHITELIST: http://back:8081,http://localhost,http://front
    depends_on:
      - db
    ports:
      - "8080:8080"
  back:
    build:
      context: ./filmotheque-back
      dockerfile: Dockerfile
    container_name: back
    environment:
      NODE_ENV: production
      PORT: 8081
      DATABASE: mongodb://admindb:admindb@db:27017/filmotheque?authSource=admin
      AUTH_URL: http://opensesame-back:8080/api/v1
      TRAKT_API_URL: https://api.trakt.tv
      TRAKT_CLIENT_ID: ${TRAKT_CLIENT_ID}
      TRAKT_CLIENT_SECRET: ${TRAKT_CLIENT_SECRET}
      TMDB_BASE_URL: https://www.themoviedb.org/movie
      RATELIMIT_MAXCONNECTIONS: 100
      RATELIMIT_WINDOWMS: 3600000
      CORS_WHITELIST: http://front:3000,http://opensesame-back:8080,http://localhost
    depends_on:
      - db
      - opensesame-back
    ports:
      - "8081:8081"
  front:
    build:
      context: ./filmotheque-front
      dockerfile: Dockerfile
    container_name: front
    environment:
      NODE_ENV: production
      BASE_URL_AUTH: http://localhost:8080/api
      BASE_URL_API: http://localhost:8081/api
    depends_on:
      - db
      - opensesame-back
      - back
    ports:
      - "80:3000"
